- name: Truning off swap
  shell: swapoff -a && free -m
  become: yes
  when: inventory_hostname in groups['masters']

- name: remove swap from fstab
  shell: sed -i '/ swap / s/^/#/' /etc/fstab
  become: yes

- name: install list of packages
  yum:
    name:
      - net-tools
      - wget
      - telnet
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - nfs-utils
    state: present

- name: add Docker repo
  shell:  yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
  become: yes


#- name: Add Docker repositorie
#  yum_repository:
#    name: docker
#    description: Docker YUM repo
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#    gpgcheck: no

#- name: Update Package Cache (yum/Amazon)
#    yum:
#    update_cache: yes

#- name: install Docker-ce
#  yum:
#    name: docker-ce-18.06.2.ce
#    state: present

- name: Creates directory docker
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: copy daemon.json
  copy:
    src: files/daemon.json
    dest: /etc/docker/
    mode : 755

- name: Creates directory docker
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Start and enable Docker systemd service
  service: name=docker state=started enabled=yes

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: daemon-reload
  shell: systemctl daemon-reload

- name: enable docker
  shell: systemctl enable docker

- name: docker restart
  shell: systemctl restart docker

- name: load netfilter probe
  shell: modprobe br-netfilter

- name: disable SELinux
  shell: setenforce 0

- name: disable SELinux
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
 
#- name: Update Package Cache (yum/Amazon)
#    yum:
#      update_cache: yes
- name: copy daemon.json
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/
    mode : 755


- name: install kubeadm kubelet kubectl
  yum:
    name: 
      - kubeadm
      - kubectl
      - kubelet
    state: present

- name: Start and enable Docker systemd service
  service: name=kubelet state=started enabled=yes

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: enable IP forwarding
  shell: echo '1' /proc/sys/net/bridge/bridge-nf-call-iptables

- name: copy k8s.conf
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/
    mode : 755


