- name: Truning off swap
  shell: swapoff -a && free -m
  become: yes
  when: inventory_hostname in groups['masters']

- name: remove swap from fstab
  shell: sed -i '/ swap / s/^/#/' /etc/fstab
  become: yes

- name: install list of packages
  yum:
    name:
      - net-tools
      - wget
      - telnet
      - yum-util
      - device-mapper-persistent-data
      - lvm2
      - nfs-utils
    state: present

- name: Add multiple repositories
  yum_repository:
      name: docker
          description: docker yum repo
	      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
	      gpgcheck: no

- name: Update Package Cache (yum/Amazon)
    tags: always
      yum:
	update_cache: yes

- name: install Docker-ce
  yum:
    name: docker-ce-18.06.2.ce
    state: present

- name: Creates directory docker
  file:
    path: /etc/docker
      state: directory

- name: copy daemon.json
  copy:
    src: files/daemon.json
    dest: /etc/docker/
    mode : 755

- name: Creates directory docker
  file:
    path: /etc/systemd/system/docker.service.d
      state: directory

- name: Start and enable Docker systemd service
  service: name=docker state=started enabled=yes

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: daemon-reload
  shell: systemctl daemon-reload

- name: enable docker
  shell: systemctl enable docker

- name: docker restart
  shell: systemctl restart docker

- name: load netfilter probe
  shell: modprobe br-netfilter

- name: disable SELinux
  shell: setenforce 0

- name: disable SELinux
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
 
- name: Add kubernetes repositories
  yum_repository:
      name: kubernetes
          description: kubernetes yum repo
	      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
	      gpgcheck: no

- name: Update Package Cache (yum/Amazon)
    yum:
      update_cache: yes

- name: install kubeadm kubelet kubectl
  yum:
    name: 
      - kubeadm
      - kubectl
      - kubelet
    state: present

- name: Start and enable Docker systemd service
  service: name=kubelet state=started enabled=yes

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: enable IP forwarding
  shell: echo '1' /proc/sys/net/bridge/bridge-nf-call-iptables

- name: copy k8s.conf
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/
    mode : 755


