- name: install Pod network
  shell: kubectl apply -f https://git.io/weave-kube-1.6 --kubeconfig /etc/kubernetes/admin.conf > pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
  when: inventory_hostname == 'Master01'

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    become: yes
  when: inventory_hostname in groups['masters']
  
