- name: get join command
  shell: kubeadm token create --print-join-command
  when: inventory_hostname == 'Master01'
  register: join_command_raw

- debug:
    msg: "{{ join_command_raw.stdout }}" 
  when: inventory_hostname == 'Master01'

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
  when: inventory_hostname == 'Master01'

- name: Enable ip_vs_rr, ip_vs_wrr, ip_vs_sh, ip_vs
  shell: modprobe -- {{ item }}
  with_items:
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - ip_vs
  when: inventory_hostname in groups['nodes']

- name: join cluster
  shell: "{{ hostvars['Master01'].join_command }}"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: inventory_hostname in groups['nodes']
  become: yes

- name: Modify the kubelet configuration to access the kube-api through the HAProxy
  shell: sed -i 's/\(\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)/{{ haproxy }}/g' /etc/kubernetes/kubelet.conf
  when: inventory_hostname in groups['nodes']

- name: Restart kubelet 
  systemd:
    name: kubelet
    state: restarted
  when: inventory_hostname in  groups['nodes']


