---
- name: Update the cache
  apt: update_cache=yes
  become: yes
  when: inventory_hostname in groups['haproxy']

- name: Install HAProxy Package
  apt: pkg=haproxy state=latest update_cache=yes
  become: yes
  when: inventory_hostname in groups['haproxy']

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  become: yes
  when: inventory_hostname in groups['haproxy']

- name: Restart service HAproxy in all cases
  service:
    name: haproxy
    state: restarted
  when: inventory_hostname in groups['haproxy']
