- name: Get kube-proxy configmap
  shell: kubectl get configmap kube-proxy --kubeconfig=/etc/kubernetes/admin.conf -n kube-system -o yaml > /tmp/kube-proxy-configmap
  when: inventory_hostname == 'Master01'

- name: Replace master ip with haproxy ip 
  shell: 'sed -i "s/server: https:\/\/\(\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)\.\)\{3\}\(1\?[0-9][0-9]\?\|2[0-4][0-9]\|25[0-5]\)/server: https:\/\/"{{ haproxy }}"/g" /tmp/kube-proxy-configmap'
  when: inventory_hostname == 'Master01'

- name: update kube-proxy configmap
  shell: kubectl create configmap kube-proxy --kubeconfig=/etc/kubernetes/admin.conf -n kube-system -o yaml --from-file=/tmp/kube-proxy-configmap --dry-run | kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f - 
  when: inventory_hostname == 'Master01'

- name: Restart kube-proxy pods
  shell: kubectl --kubeconfig /etc/kubernetes/admin.conf delete pod -l k8s-app=kube-proxy -n kube-system --grace-period=0 --force
  when: inventory_hostname == 'Master01'
